export const routes = {
  dashboard: "/",
  view_shop: "/view_shop",
  subscriptions: "/subscriptions",
  store_design: "/store_design",
  share_shop: "/share_shop",
  settings: "/settings",
  payment_options: "/view_shop",
  orders: "/orders",
  integrations: "/integrations",
  delivery_options: "/delivery_options",
  customer_support: "/customer_support",
  catalogue: "/catalogue",
  marketing: "/marketing",
  customers: "/customers",
  discount_codes: "/marketing/discount_codes",
  exit_intent: "/marketing/exit_intent",
  logout: "logout",
};
